config/routes.rb
Tunr2::Application.routes.draw do

  root 'welcome#index'

  resources :users, except: [:index] do
    resources :owned_songs, only: [:index, :show]
    resources :playlists, shallow: true
  end

  resources :artists, only: [:index, :show] do
    resources :songs, only: [:show], shallow: true do
      member do
        post "purchase"
      end
    end
  end

  resource :session, only: [:create, :new, :destroy]
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :balance, numericality: { greater_than_or_equal_to: 0 }

  has_secure_password
  has_and_belongs_to_many :songs

  def purchase(song)
    if afford?(song) && pay_for(song)
      self.songs << song
    end
  end

  def afford?(song)
    balance >= song.price
  end

  def pay_for(song)
    self.balance -= song.price
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  # GET /artists
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  def show
    @artist = Artist.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in"
      redirect_to(user)
    else
      flash[:notice] = "Incorrect Login. Try again."
      redirect_to(new_session_path)
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to(root_path)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def show
    @song = Song.find(params[:id])
  end

  def purchase
    @song = Song.find(params[:id])

    if current_user.purchase(@song)
      redirect_to user_path(current_user)
    else
      render :show
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in!, :authorize_user!, only: [:edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def authorize_user!
    @user = User.find(params[:id])
    redirect_to new_session_path unless current_user?(@user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def logged_in!
    redirect_to new_session_path unless logged_in?
  end

  def current_user?(user)
    current_user == user
  end
end

app/views/artists/index.html.erb
<h1>Artists</h1>


<ul>
  <% @artists.each do |artist| %>
    <li>
      <td><%= link_to artist.name, artist %></td>
    </li>
  <% end %>
</ul>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>

<h3>Songs:</h3>
<ul>
  <% @artist.songs.each do |song| %>
    <li><%= link_to song.name, song %></li>
  <% end %>
</ul>

<%= link_to 'Back', artists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tunr2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if logged_in? %>
    <nav>
      <ul>
        <li>Welcome, <%= current_user.email %> | </li>
        <li>Balance: $<%= current_user.balance.to_f %></li>
        <li><%= link_to "Logout", session_path, method: :delete %></li>
      </ul>
    </nav>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/songs/show.html.erb
<h1><%= @song.name %></h1>
<p><%= @song.artist.name %></p>

<iframe src="https://embed.spotify.com/?uri=<%= @song.spotify_uri %>" width="300" height="380" frameborder="0" allowtransparency="true"></iframe>

<% if logged_in? %>
  <div>
    <%= link_to "Purchase", purchase_song_path(@song), method: :post %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/welcome/index.html.erb
<h1> Welcome to Tunr!</h1>

<%= link_to "Sign Up!", new_user_path %>
<%= link_to "Sign In", new_session_path %>
<%= link_to "Browse Artists", artists_path %>